# Generated by Django 5.0 on 2023-12-17 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='operator_airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircraft_set', to='airline_api.airline'),
        ),
    ]
